from app import db, bcrypt
from models import User, Topic, Motion, Argument, Vote
import datetime

db.create_all()

# insert
db.session.add(User("Natalie", "nat@natalie.com", "password"))
db.session.add(User("Tyler", "ty@tyler.com", "password"))
db.session.add(User("Kevin", "kev@kevin.com", "password"))
db.session.add(User("David","dav@david.com", "password"))
db.session.add(User("Nick","nic@nick.com", "password"))

db.session.add(Topic("Economy", "The federal government should impose a national $15/hr minimum wage.", 2)) 
db.session.add(Topic("International Relations", "The immediate re-militarization of NATO should be a top priority in advancing U.S. national security interests.", 5)) 
db.session.add(Topic("Economy", "Something something about the economy.", 2)) 
db.session.add(Topic("Environment", "Something something about the environment.", 5))
db.session.add(Topic("International Relations", "Something something about international relations.", 3)) 

# topic_id, user_id, user_procon
db.session.add(Motion(1, 1, False))
db.session.add(Motion(1, 2, False))
db.session.add(Motion(1, 3, True))
db.session.add(Motion(1, 4, True))
db.session.add(Motion(1, 5, False))
db.session.add(Motion(2, 1, True))
db.session.add(Motion(2, 2, False))
db.session.add(Motion(2, 3, True))
db.session.add(Motion(2, 4, True))
db.session.add(Motion(2, 5, False))
db.session.add(Motion(3, 1, True))
db.session.add(Motion(3, 2, True))
db.session.add(Motion(3, 3, True))
db.session.add(Motion(3, 4, False))
db.session.add(Motion(3, 5, False))
db.session.add(Motion(4, 1, False))
db.session.add(Motion(4, 2, True))
db.session.add(Motion(4, 3, True))
db.session.add(Motion(4, 4, False))
db.session.add(Motion(4, 5, True))

# abstract, argument, author_id, motion_id
db.session.add(Argument(False, "DON\'T TREAD ON ME!", "OBAMA\'S NEW SOCIALISM IS ALL ABOUT GOVERNMENT HANDOUTS TO THE POOR AND LAZY", 1, 1))
db.session.add(Argument(False, "A $15/hr minimum wage is relatively high-risk to vulnerable workers and is poor a policy choice relative to other politically feasible options.", "Although the employment effects are empirically mixed, we should not risk pricing vulnerable low-skilled workers out of the labor market and passing on higher costs to consumers in these industries (most of whom are themselves low-income consumers). There are other politically feasible policy options which are low-risk to workers and directly target poverty. These policy options include direct cash subsidies (e.g. basic income or negative income tax) and refundable tax credits (e.g. earned income tax credits).", 2, 2))
db.session.add(Argument(False, "The minimum wage hurts small businesses more than large corporations.", "Small businesses are the lifeblood of the American economy and increases in the minimum wage will destroy these jobs. Why stop at $15 an hour? Why not $100 an hour?! Why not just pay everyone in cocaine and unicorns?", 3, 3))
db.session.add(Argument(False, "A $15/hr minimum wage would hurt society\'s most disadvantaged people looking for work even if it doesn\'t increase overall unemployment.", "If I\'m an employer who is now forced to hire at a higher wage then I will expect greater productivity to off-set the additional cost. Therefore, I will be more likely to hire an older experienced worker who came out of retirement to work for the higher wage instead of a troubled minority youth who is in desperate need of work.", 4, 4))     
db.session.add(Argument(False, "Just expand the earned income tax credit (EITC) instead!", "The EITC is far more effective at alleviating poverty since it's a direct cash subsidy instead of a dangerously high price floor which is what a $15/hr minimum wage is.", 5, 5))

db.session.add(Argument(False, "WAR IS NOT THE ANSWER!!", "THE UNITED STATES SHOULD STOP TRYING TO ASSERT IT\'S HEGEMONY IN THE REGION.", 1, 6))
db.session.add(Argument(False, "At this stage it is both unwise and unnecessary to provoke Putin. There are other less aggressive options.", "Western sanctions coupled with the low energry prices are crippling Russia\'s economy. This in turn is reducing domestic support.", 2, 7))
db.session.add(Argument(False, "Kevin\'s con abstract.", "Kevin\'s con argument.", 3, 8))
db.session.add(Argument(False, "David\'s con abstract.", "David\'s con argument.", 4, 9))
db.session.add(Argument(False, "Nick\'s con abstract.", "Nick\'s con argument.", 5, 10))

db.session.add(Argument(False, "Natalie\'s con abstract.", "Natalie\'s con abstract.", 1, 11))
db.session.add(Argument(False, "Tyler\'s con abstract", "Tyler\'s con argument.", 2, 12))
db.session.add(Argument(False, "Kevin\'s con abstract.", "Kevin\'s con argument.", 3, 13))
db.session.add(Argument(False, "David\'s con abstract.", "David\'s con argument.", 4, 14))
db.session.add(Argument(False, "Nick\'s con abstract.", "Nick\'s con argument.", 5, 15))

db.session.add(Argument(False, "Natalie\'s con abstract.", "Natalie\'s con abstract.", 1, 16))
db.session.add(Argument(False, "Tyler\'s con abstract", "Tyler\'s con argument.", 2, 17))
db.session.add(Argument(False, "Kevin\'s con abstract.", "Kevin\'s con argument.", 3, 18))
db.session.add(Argument(False, "David\'s con abstract.", "David\'s con argument.", 4, 19))
db.session.add(Argument(False, "Nick\'s con abstract.", "Nick\'s con argument.", 5, 20))

db.session.add(Argument(True, "WE ARE THE 1%!", "AND WE WILL NOT TOLERATE THE SYSTEMATIC OPPRESSION AND EXTORTION OF WORKERS BY GREEDY CORPORATIONS.", 1, 1))
db.session.add(Argument(True, "The minimum wage ensures that employers invest in their employees and is overall good for the economy.", "The industry demand for labor is much more inelastic than most economists think. A $15/hr minimum wage will not cause significant levels unemployment and, therefore, helps redistribute profits from investors and corporate executives to the workers without significant unemployment risks. What's more, labor has a greater propensity to consume with their income which further stimulates overall aggregate demand.", 2, 2))
db.session.add(Argument(True, "Everyone deserves a living wage!", "The share of income to labor has fallen steadily since the decline of the welfare state in the late 1960s.", 3, 3))
db.session.add(Argument(True, "Everyone that puts in a full day\'s worth of hard work deserves a modest standard of living.", "There's enough millionaires and, even billionaires, out there to ensure the rest of us are well taken care of.", 4, 4))
db.session.add(Argument(True, "I would rather deal with robots instead of human cashiers anyways.", "All other things equal, a higher minimum wage will encourage firms to substitute capital for labor. This will accelerate technological progress in our everyday lives!", 5, 5))

db.session.add(Argument(True, "PUTIN\'S RUSSIA IS THE NEW EVIL EMPIRE", "WE SHOULD IMMEDIATELY RE-MILITARIZE NATO IN PREPARATION FOR A CONFRONTATION.", 1, 6))
db.session.add(Argument(True, "Tyler\'s pro abstract.", "Tyler\'s pro argument.", 2, 7))
db.session.add(Argument(True, "Kevin\'s pro abstract.", "Kevin\'s pro argument.", 3, 8))
db.session.add(Argument(True, "David\'s pro abstract.", "David\'s pro argument.", 4, 9))
db.session.add(Argument(True, "Nick\'s pro abstract.", "Nick\'s pro argument.", 5, 10))

db.session.add(Argument(True, "Natalie\'s pro abstract.", "Natalie\'s pro abstract.", 1, 11))
db.session.add(Argument(True, "Tyler\'s pro abstract", "Tyler\'s pro argument.", 2, 12))
db.session.add(Argument(True, "Kevin\'s pro abstract.", "Kevin\'s pro argument.", 3, 13))
db.session.add(Argument(True, "David\'s pro abstract.", "David\'s pro argument.", 4, 14))
db.session.add(Argument(True, "Nick\'s pro abstract.", "Nick\'s pro argument.", 5, 15))

db.session.add(Argument(True, "Natalie\'s pro abstract.", "Natalie\'s pro abstract.", 1, 16))
db.session.add(Argument(True, "Tyler\'s pro abstract", "Tyler\'s pro argument.", 2, 17))
db.session.add(Argument(True, "Kevin\'s pro abstract.", "Kevin\'s pro argument.", 3, 18))
db.session.add(Argument(True, "David\'s pro abstract.", "David\'s pro argument.", 4, 19))
db.session.add(Argument(True, "Nick\'s pro abstract.", "Nick\'s pro argument.", 5, 20))

# arg_id, motion_id, value, user_id
db.session.add(Vote(2, 2, 9, 1)) 
db.session.add(Vote(3, 3, 3, 1))
db.session.add(Vote(4, 4, 7, 1))
db.session.add(Vote(5, 5, 8, 1))
db.session.add(Vote(1, 1, 2, 2)) 
db.session.add(Vote(3, 3, 2, 2))
db.session.add(Vote(4, 4, 8, 2))
db.session.add(Vote(5, 5, 9, 2)) 
db.session.add(Vote(1, 1, 2, 5)) 
db.session.add(Vote(2, 2, 10, 5))
db.session.add(Vote(3, 3, 3, 5))
db.session.add(Vote(4, 4, 8, 5)) 
db.session.add(Vote(21, 1, 4, 3)) 
db.session.add(Vote(22, 2, 9, 3))
db.session.add(Vote(24, 4, 8, 3))
db.session.add(Vote(25, 5, 8, 3))
db.session.add(Vote(21, 1, 2, 4)) 
db.session.add(Vote(22, 2, 10, 4))
db.session.add(Vote(23, 3, 3, 4))
db.session.add(Vote(25, 5, 8, 4))
db.session.add(Vote(6, 6, 2, 2)) 
db.session.add(Vote(8, 8, 2, 2))
db.session.add(Vote(9, 9, 3, 2))
db.session.add(Vote(10, 10, 9, 2))
db.session.add(Vote(6, 6, 2, 5)) 
db.session.add(Vote(7, 7, 9, 5))
db.session.add(Vote(8, 8, 4, 5))
db.session.add(Vote(9, 9, 3, 5))
db.session.add(Vote(27, 7, 9, 1)) 
db.session.add(Vote(28, 8, 8, 1))
db.session.add(Vote(29, 9, 7, 1))
db.session.add(Vote(30, 10, 7, 1))
db.session.add(Vote(26, 6, 3, 3))
db.session.add(Vote(27, 7, 9, 3))
db.session.add(Vote(29, 9, 7, 3))
db.session.add(Vote(30, 10, 8, 3))
db.session.add(Vote(26, 6, 6, 4))
db.session.add(Vote(27, 7, 8, 4))
db.session.add(Vote(28, 8, 7, 4))
db.session.add(Vote(30, 10, 7, 4))


#commit
db.session.commit()